type Query {
    hello: String
    paramsRevise(fName: String, lName: String): String
    sampleRequestJson(sampleRequest: SampleRequest): String
    studentData(id: String) : StudentResponse
}
input SampleRequest {
    firstName: String!
    lastName: String
}
type StudentResponse {
    id: ID
    firstName: String
    lastName: String
    email: String
    street: String
    city: String
    fullName: String
    learningSubjects(subjectNameFilter: SubjectNameFilter): [SubjectResponse]

}
type SubjectResponse {
    id: ID
    subjectName: String
    marksObtained: Float
}
enum SubjectNameFilter {
    Java,
    MySQL,
    MongoDB
}
